apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: __namespace__
spec:
  type: ClusterIP
  selector:
    app: user
  ports:
    - protocol: TCP
      port: 80
      targetPort: 10004
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: __namespace__
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      serviceAccountName: odp-admin
      containers:
        - name: user
          image: '__docker_registry_server__/datanimbus.io.user:__release__'
          ports:
            - containerPort: 10004
          livenessProbe:
            httpGet:
              path: /rbac/internal/health/live
              port: 10004
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /rbac/internal/health/ready
              port: 10004
            initialDelaySeconds: 10
            periodSeconds: 10
          envFrom:
          - configMapRef:
              name: config
      imagePullSecrets:
        - name: regsecret        

